import { readFile, stat } from 'node:fs/promises'
import path from 'node:path'
import type { SiteData } from './site-types'

export * from './site-types'

const DATA_FILE = path.join(process.cwd(), 'data', 'sites.json')

let cached: { data: SiteData; mtimeMs: number } | null = null

/**
 * The dataset is generated by `scripts/build-dataset.mjs` and committed, so a
 * missing or unreadable file is a deployment fault, not a condition to paper
 * over with an empty list.
 *
 * The cache is keyed on the file's mtime rather than held forever: the file is
 * meant to be regenerated, and a long-running dev server that kept serving the
 * copy it read at boot handed phones a *older* dataset than the one they
 * already had.
 */
export async function loadSites(): Promise<SiteData> {
  const { mtimeMs } = await stat(DATA_FILE)
  if (cached && cached.mtimeMs === mtimeMs) return cached.data

  const raw = await readFile(DATA_FILE, 'utf8')
  const data = JSON.parse(raw) as SiteData
  if (!Array.isArray(data.sites) || data.sites.length === 0) {
    throw new Error(`${DATA_FILE} holds no sites — run: node scripts/build-dataset.mjs`)
  }
  cached = { data, mtimeMs }
  return data
}
